"""Deterministic semantic-layer document governance (SEM-003 hardening).

The active semantic directory (``semantic/metrics/``) is a HUMAN-governed
surface: metric definitions may be drafted by an agent but must carry an
explicit human owner declaration and must never be auto-generated by
scaffolds or tools (SEM-003). This module provides the deterministic doc
validation the semantic discovery path enforces fail-closed: an ownerless
or definition-less metric doc is excluded from discovery and never served
as a semantic metric.

Applicable rules: SEM-003, DOC-002, HOOK-001, HOOK-004.
"""

from __future__ import annotations

import re

from .gates import GateDecision

_OWNER_LINE = re.compile(r"^\s*[-*]\s*owner\s*:", re.IGNORECASE | re.MULTILINE)
_DEFINITION_LINE = re.compile(
    r"^\s*[-*]\s*definition\s*:", re.IGNORECASE | re.MULTILINE)


def validate_semantic_metric_doc(content: str) -> GateDecision:
    """Validate one semantic metric document against the governance floor.

    Returns a ``pass`` decision when the doc carries both an ``owner:`` and
    a ``definition:`` declaration; otherwise a ``block`` decision carrying
    the missing field and its recovery. The owner declaration is the
    human-governance marker (SEM-003); the definition is required metadata
    (DOC-002).
    """
    if _OWNER_LINE.search(content or "") is None:
        return GateDecision.block(
            rule_ids=("SEM-003", "HOOK-004"),
            evidence_refs=("semantic:doc",),
            reason="semantic metric doc has no owner declaration; the "
                   "semantic layer is human-governed (SEM-003)",
            recovery="Add an 'owner: <human owner>' line to the metric doc "
                     "(tools/scaffolds must never auto-generate semantic docs)",
        )
    if _DEFINITION_LINE.search(content or "") is None:
        return GateDecision.block(
            rule_ids=("DOC-002", "HOOK-004"),
            evidence_refs=("semantic:doc",),
            reason="semantic metric doc has no definition declaration "
                   "(DOC-002)",
            recovery="Add a 'definition: ...' line to the metric doc",
        )
    return GateDecision.pass_(
        rule_ids=("SEM-003", "DOC-002"),
        evidence_refs=("semantic:doc",),
        reason="semantic metric doc carries owner and definition",
        recovery="No action required",
    )
